### PR TITLE
ARTP-1326 disable RFQ when max exceeded

### PR DESCRIPTION
**Pull request by mhamdar**
Disabling RFQ booking when the user has entered a notional value that exceeds our hardcoded limit.
e9b5eacee82045dee5cce7f92c336944
6dc888456f4f1fa7798a55d6c421942c

### CODE REVIEW

**Comment by stewart-adaptive** [comment]
is it ok to still show the initiate RFQ button in this state?

**Comment by mhamdar** [comment]
> is it ok to still show the initiate RFQ button in this state?

**Comment by mhamdar** [comment]
> is it ok to still show the initiate RFQ button in this state?

I think this is the approach we had discussed (@rikoe ?), what did you have in mind?

**Review by chuck-adaptive — APPROVED** [review]
Pending UX decision, 👍

**Review by rikoe — APPROVED** [review]

**Pull request merged**
