### PR TITLE
refactor(new-client): fix tile chart jump point

### PR DESCRIPTION
**Pull request by slcfv3**
-temporary fix the tile chart jump point issue

### CODE REVIEW

**Review by josepot — APPROVED** [review]
Thanks @slcfv3 ! 

We should create a task on the board to check why the stream returned by the `getRemoteProcedureCall$` function doesn't automatically complete after emitting its first value. Although, in the meanwhile, this is great.

**Comment by slcfv3** [comment]
> Thanks @slcfv3 !
> 
> We should create a task on the board to check why the stream returned by the `getRemoteProcedureCall$` function doesn't automatically complete after emitting its first value. Although, in the meanwhile, this is great.

Great, do you want me to create a ticket on kanban?

**Comment by josepot** [comment]
> > Thanks @slcfv3 !
> > We should create a task on the board to check why the stream returned by the `getRemoteProcedureCall$` function doesn't automatically complete after emitting its first value. Although, in the meanwhile, this is great.
> 
> Great, do you want me to create a ticket on kanban?

Yes, please. Thanks @slcfv3 !

**Comment by slcfv3** [comment]
> > > Thanks @slcfv3 !
> > > We should create a task on the board to check why the stream returned by the `getRemoteProcedureCall$` function doesn't automatically complete after emitting its first value. Although, in the meanwhile, this is great.
> > 
> > 
> > Great, do you want me to create a ticket on kanban?
> 
> Yes, please. Thanks @slcfv3 !

done, ticket number 706

**Pull request merged**
