### PR TITLE
fix(new-client): add/remove position bubbles (807)

### PR DESCRIPTION
**Pull request by josepot**
I just enjoy deleting code... :sweat_smile:

### CODE REVIEW

**Comment by iprado78** [comment]
> I just enjoy deleting code... 😅

Possible to convert the drag event into a takeUntil for even more free bits?

**Review by iprado78 — APPROVED** [review]

**Review by garyadaptive — CHANGES_REQUESTED** [review]
Let's hold off merging this; I think there's still something not quite right. I need to dig into it a bit, but the bubbles are not updating correctly to show positions. Open the old and new client side-by-side and place some trades, you should see the new client gets stuck and only syncs the bubbles after a reload.

**Comment by josepot** [comment]
> Let's hold off merging this; I think there's still something not quite right. I need to dig into it a bit, but the bubbles are not updating correctly to show positions. Open the old and new client side-by-side and place some trades, you should see the new client gets stuck and only syncs the bubbles after a reload.

You are correct! Thanks for catching that @garyadaptive! I was so focus on making the addition/deletion work that I didn't notice that the updates are not working correctly... I think that I know how to fix it, though. Thanks again!

**Comment by josepot** [comment]
I think that it should work fine now... I will add more snapshot tests if it's confirmed that this is the expected behavior.

**Review by garyadaptive — APPROVED** [review]
All looks good to me :)

**Comment by josepot** [comment]
> Possible to convert the drag event into a takeUntil for even more free bits?

Sorry, but I'm not following... What do you mean?

**Comment by iprado78** [comment]
> > Possible to convert the drag event into a takeUntil for even more free bits?
> 
> Sorry, but I'm not following... What do you mean?

I haven't looked carefully at the full context of the drag event, and I know we are mostly not using Rx for data flow in Analytics, but it seems like you could easily model the drag event and the chart side effects as a set of streams (take the 

> > I just enjoy deleting code... 😅
> 
> Possible to convert the drag event into a takeUntil for even more free bits?

Concat drag event with chart side effects until drag event ends.  You are essentially doing this already just not in Rx.  Better your way with the Analytics code we have.  Just imagining what a more Rx version of the Analytics code would look like.

**Pull request merged**
