### PR TITLE
remove npm cache

### PR DESCRIPTION
**Pull request by tdeheurles**

### CODE REVIEW

**Comment by KeithWoods** [comment]
@tdeheurles bump, what's the status of this?

**Comment by tdeheurles** [comment]
Some build fail on circlci due to npm cache when we update packages.
I think this PR should be deleted as we didn't have that kind of failing in the last weeks.

Could we have your point of view @raybooysen please ?

**Comment by raybooysen** [comment]
I think we should get rid of this PR.

On 14 April 2016 at 12:01, thibault deheurles <notifications@github.com>
wrote:

> Some build fail on circlci due to npm cache when we update packages.
> I think this PR should be deleted as we didn't have that kind of failing
> in the last weeks.
>
> Could we have your point of view @raybooysen
> <https://github.com/raybooysen> please ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/203#issuecomment-209879779>
>

-- 
 

*This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. Any views or 
opinions expressed are solely those of the author and do not necessarily 
represent those of Adaptive Financial Consulting Ltd. *

*If you are not the intended recipient of this email, you must neither take 
any action based upon its contents, not copy nor show it to anyone.*

*Please contact the sender if you believe you have received this email in 
error.*

*Adaptive Financial Consulting Ltd is a company registered in England and 
Wales. Registered number: 08105955. Registered office: 2nd floor, 11 
Leadenhall Street, London EC3 V1LP.*

**Comment by raybooysen** [comment]
I think this should be merged.  Less chance of breakage and we also are not maintaining the cache so it's pretty out of date.

**Pull request closed without merging**
