### PR TITLE
Credit check

### PR DESCRIPTION
**Pull request by fdore**
#46

### CODE REVIEW

**Comment by KeithWoods** [comment]
nice work. 

@fdore has this been checked with the excel sheet that open fin chats to?

**Comment by fdore** [comment]
@KeithWoods What do you mean exactly? @zeala is currently looking at the excel integration part.

**Comment by KeithWoods** [comment]
I believe when running in open fin and you book a trade there is functionality to chat to an excel spreadsheet to check if there is credit for the transaction.

**Comment by fdore** [comment]
Do you mean that app http://adaptiveconsulting.github.io/ReactiveTraderJS/install/LimitChecker/LimitChecker.application as opposed to Excel?

**Comment by KeithWoods** [comment]
oh, yeah sorry must be that and not excel

**Comment by fdore** [comment]
Yeah, that's the app I have tested against.

**Pull request merged**
