### PR TITLE
[WIP] switch initial deployment to hive mechanism

### PR DESCRIPTION
**Pull request by tdeheurles**
##### This is a big PR that totally change the deploy mechanism.

A big part of the bash deployment mechanism are re-written in python and run into a container. It adds a dependencie to [hive](https://tdeheurles.gitbooks.io/hive/content/) but remove most of the corresponding content. The work implies some big changes and is still in progress.

##### Todo

- [x] switch from circleci to jenkins
- [ ] write documentation specific to ReactiveTrader (The one for the Hive utilisation is done)
- automate jenkins startup on the kubernetes cluster with hive
  - [ ] deployment
  - [ ] jenkins deployment documentation
- Hive:
  - [x] Hive will certainly have an issue with its rm_working_directory
- [ ] Test jenkins push mechanism
- [ ] Control that Jenkins is green by rebasing master in hive-deployment for each circleci master build
- [ ] Setup Github-Jenkins integration

##### Why

- Maximum of the code to build/deploy now run into a container. It `limits portability issues`.
- The devops code is written in Python instead of bash and could be easily tested
- The hive tool can be used to `build run and deploy reactiveTrader` but also to `do most of the cloud setup`. Everything is at the same place and can be `easily documented`. Utilisation is more intuitive with the `CLI help`.
- To init another project, we can just copy the `hive file` and start writing specific code. The devops code is `only writen once`.
- We build our container directly on the cluster. This should be part to reduce time consumption as everything run in the same cloud.
- We won't have to `tar`/`untar` the cache in order to save time for the builds. This will also save a lot of time.

#### CircleCI to jenkins

The test can't pass anymore in CircleCi. Hive is a container that start other containers and it can't be done into CircleCi as it runs a DockerInDocker.

A build in CircleCi start a docker container where our code run. So the docker setup in CircleCi install docker daemon into a docker container. This process is named DockerInDocker. The problem is the limitation added by this solution.

Jenkins will run in our kubernetes cluster as a container (easily started from hive). But this container will have the permission to access the docker daemon of our kubernetes cluster. 

You can find our jenkins here: [https://jenkins-ci.adaptivecluster.com/](https://jenkins-ci.adaptivecluster.com/).

### CODE REVIEW

**Comment by tdeheurles** [comment]
@qiming:

The entrypoint for all commands is the `hive` script at the root of the project. It's a little bash bootstrap that first download it's content (easy way to update) and start containers or manage the docker-toolbox VM.

To understand the following commands, the better place is the [hive documentation](https://github.com/tdeheurles/hive). The walkthrough should be done in something like 15 minutes. If you do it, can you write the time used and the different problems etc.

##### To build
```
# build_id is a string
./hive do build devops/reactivetrader all id <Build_id>
```

##### To run
```
./hive do run devops/reactivetrader all id <Build_id> configuration release
```

##### To push
```
./hive do push devops/reactivetrader all id <Build_id>
```

##### To deploy
```
# Connect to gcloud first time
./hive gcloud init
./hive kubernetes deploy devops/reactivetrader <EnvironmentName> <Build_id>
```

**Comment by tdeheurles** [comment]
@qiming

For `jenkins`, the container project is in the folder `devops/tooling/jenkins`. 

This part of the project is not working e2e. 

Like before, to build/push/deploy:
```
# build
./hive do build devops/tooling/jenkins jenkins id <build_id>

# push
./hive do push devops/tooling/jenkins jenkins id <build_id>

# deploy
./hive kubernetes deploy devops/tooling/jenkins jenkins ... <todo> ...
```

**Comment by tdeheurles** [comment]
@odeheurles, @qooroo :
I'm not sure what is the jenkins good place.

Technically, it should be fine to run directly on kubernetes and so we don't have to manage a different VM. But I need to give `jenkins` the access to the docker daemon. If jenkins security is compromised, the node is certainly compromised (and maybe the cluster too).

Anyway, for production, I think we should have a different cluster, so the problem is maybe not so important ...

What's your position on that ?

**Comment by tdeheurles** [comment]
@qooroo I made some progress on the jenkins server:
- The deployment is working
- I have upgraded our cluster to last version and fix some issue with docker version (docker version start to  be different everywhere as they update really often)
- I have setup a ReactiveTrader build on that jenkins
- hive works on it
- The build is green and the containers are built

But:
- The test mechanism need to be implemented in hive
- Hive will certainly have an issue with its rm_working_directory

**Comment by JPWatson** [comment]
Closing for now

**Pull request closed without merging**
