### PR TITLE
remove docker-toolbox issue

### PR DESCRIPTION
**Pull request by tdeheurles**
This issue has been fixed on docker-toolbox

### CODE REVIEW

**Comment by raybooysen** [comment]
@tdeheurles can I merge this?

**Comment by KeithWoods** [comment]
@tdeheurles bump, what's the status of this?

**Comment by tdeheurles** [comment]
It can be merged

**Comment by KeithWoods** [comment]
@tdeheurles this is odd, the status checks have passed but the merge button is disabled. Either I'm missing something or this is some odd github bug?

**Comment by tdeheurles** [comment]
I have the same... It’s just the removal of a little part of the
documentation. I don t understand this issue with merge. If no one can
merge. Juste delete and I will push a new one.

**Comment by KeithWoods** [comment]
deleted

**Comment by raybooysen** [comment]
You can also just touch a file and push to get a commit and therefore a new
build

On 15 April 2016 at 08:34, Keith Woods <notifications@github.com> wrote:

> deleted
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/208#issuecomment-210330030>
>

-- 
 

*This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. Any views or 
opinions expressed are solely those of the author and do not necessarily 
represent those of Adaptive Financial Consulting Ltd. *

*If you are not the intended recipient of this email, you must neither take 
any action based upon its contents, not copy nor show it to anyone.*

*Please contact the sender if you believe you have received this email in 
error.*

*Adaptive Financial Consulting Ltd is a company registered in England and 
Wales. Registered number: 08105955. Registered office: 2nd floor, 11 
Leadenhall Street, London EC3 V1LP.*

**Pull request closed without merging**
