### PR TITLE
ARTP-1379: Execute Trades from Launcher

### PR DESCRIPTION
**Pull request by pmilla1606**
This PR:

- Adds intents to Google Dialog flow (https://dialogflow.cloud.google.com/#/agent/adaptive-trader/intents)
- Adds `<InlineTradeExecution />` component and functionality to execute trades from launcher.

https://user-images.githubusercontent.com/3123490/106319409-67de0f80-623f-11eb-8e25-63d5bf02e49a.mov

### CODE REVIEW

**Comment by garyadaptive** [comment]
Looking good so far! Once the build is green, let's put a "preview" label on this PR. It seems like a good opportunity to spin up a PR deployment.

**Comment by pmilla1606** [comment]
@garyadaptive discussed changes made and refactored to be cleaner.

**Review by garyadaptive — CHANGES_REQUESTED** [review]
Nice one, I have it working locally (sadly I can't use the deployed version as we haven't provisioned all the config necessary to run the NLP service for a PR build, but that's now on my backlog).

A couple of thoughts:
* We should add a button to start executing the trade. At the moment, as soon as the entered search term resolves to the trade execution intent, it starts the execution flow. We should change this to show a button once the intent is detected and have that kick off the execution flow.
* When we close the full takeover notification (regardless of success, reject or cancel) we should clear the search input.
* I think we could add a little left padding to the takeover notification to balance it visually.

Otherwise it's looking really slick. It's going to be an amazing addition to our sales demos. Great job!

**Comment by pmilla1606** [comment]
@garyadaptive all looks good and everything's green. Once somebody approves I can go ahead and merge.

**Review by garyadaptive — APPROVED** [review]

**Pull request merged**
