### PR TITLE
Fixup running inside OpenFin

### LINKED ISSUE #911: Fails to start inside OpenFin
```shell
$ npm run start:openfin:local 
```

Output:
```
> npm-run-all -p openfin start:local


> reactive-trader-cloud@2.1.0 openfin /home/mozmorris/Code/Adaptive/ReactiveTraderCloud/src/client
> openfin -c public/config/openfin/local.json -l


> reactive-trader-cloud@2.1.0 start:local /home/mozmorris/Code/Adaptive/ReactiveTraderCloud/src/client
> cross-env REACT_APP_ENV=local npm run start-js

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/mozmorris/Code/Adaptive/ReactiveTraderCloud/src/client/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/mozmorris/Code/Adaptive/ReactiveTraderCloud/src/client/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/mozmorris/Code/Adaptive/ReactiveTraderCloud/src/client/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
npm ERR! code ELIFECYCLE
```

### PR DESCRIPTION
**Pull request by mozmorris**
This fixes #911 by:

1. Bumping the version of `openfin-cli` - fixes runtime error.
2. Introducing a small delay before launching OpenFin - fixes connection error where local dev server wasn't running.

### CODE REVIEW

**Comment by keshaldesai** [comment]
We could also make a ping script that checks a port until it opens.

**Comment by mozmorris** [comment]
After @ianchan035 added OpenFin to `hydra-demo`, we had the same issue. So we looked at how AdaptiveTrader handled it.... and of course it didn't. Firstly running OpenFin didn't even work here, and then when that was fixed, sure enough the same issue.

**Comment by mozmorris** [comment]
It's worth nothing, that sometimes it does work without the sleep.... the 5 seconds I felt was more than enough as the initial compilation takes longer than that anway.

**Comment by keshaldesai** [comment]
Thanks @mozmorris!

**Pull request merged**
